# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20170201203212) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "assets", force: :cascade do |t|
    t.integer  "user_id"
    t.integer  "stock_id"
    t.datetime "created_at",       null: false
    t.datetime "updated_at",       null: false
    t.float    "high"
    t.float    "low"
    t.datetime "sent_at"
    t.boolean  "previous_success"
    t.datetime "start_time"
    t.datetime "finish_time"
  end

  create_table "displaytexts", force: :cascade do |t|
    t.integer  "payload_id"
    t.string   "ask_display_text"
    t.string   "average_daily_volume_display_text"
    t.string   "bid_display_text"
    t.string   "book_value_display_text"
    t.string   "change_display_text"
    t.string   "change_from_fiftyday_moving_average_display_text"
    t.string   "change_from_two_hundredday_moving_average_display_text"
    t.string   "change_from_year_high_display_text"
    t.string   "change_from_year_low_display_text"
    t.string   "change_percent_change_display_text"
    t.string   "changein_percent_display_text"
    t.string   "currency_display_text"
    t.string   "days_high_display_text"
    t.string   "days_low_display_text"
    t.string   "days_range_display_text"
    t.string   "dividend_pay_date_display_text"
    t.string   "dividend_share_display_text"
    t.string   "dividend_yield_display_text"
    t.string   "earnings_share_display_text"
    t.string   "ebitda_display_text"
    t.string   "eps_estimate_current_year_display_text"
    t.string   "eps_estimate_next_quarter_display_text"
    t.string   "eps_estimate_next_year_display_text"
    t.string   "ex_dividend_date_display_text"
    t.string   "fiftyday_moving_average_display_text"
    t.string   "last_trade_date_display_text"
    t.string   "last_trade_price_only_display_text"
    t.string   "last_trade_time_display_text"
    t.string   "last_trade_with_time_display_text"
    t.string   "market_capitalization_display_text"
    t.string   "name_display_text"
    t.string   "oneyr_target_price_display_text"
    t.string   "open_display_text"
    t.string   "pe_ratio_display_text"
    t.string   "peg_ratio_display_text"
    t.string   "percebt_change_from_year_high_display_text"
    t.string   "percent_change_display_text"
    t.string   "percent_change_from_fiftyday_moving_average_display_text"
    t.string   "percent_change_from_two_hundredday_moving_average_display_text"
    t.string   "percent_change_from_year_low_display_text"
    t.string   "previous_close_display_text"
    t.string   "price_book_display_text"
    t.string   "price_eps_estimate_current_year_display_text"
    t.string   "price_eps_estimate_next_year_display_text"
    t.string   "price_sales_display_text"
    t.string   "response_code_display_text"
    t.string   "short_ratio_display_text"
    t.string   "stock_exchange_display_text"
    t.string   "symbol_display_text"
    t.string   "two_hundredday_moving_average_display_text"
    t.string   "volume_display_text"
    t.string   "year_high_display_text"
    t.string   "year_low_display_text"
    t.string   "year_range_display_text"
    t.datetime "created_at",                                                     null: false
    t.datetime "updated_at",                                                     null: false
  end

  create_table "payloads", force: :cascade do |t|
    t.integer "asset_id"
    t.boolean "ask"
    t.boolean "average_daily_volume"
    t.boolean "bid"
    t.boolean "book_value"
    t.boolean "change"
    t.boolean "change_from_fiftyday_moving_average"
    t.boolean "change_from_two_hundredday_moving_average"
    t.boolean "change_from_year_high"
    t.boolean "change_from_year_low"
    t.boolean "change_percent_change"
    t.boolean "changein_percent"
    t.boolean "currency"
    t.boolean "days_high"
    t.boolean "days_low"
    t.boolean "days_range"
    t.boolean "dividend_pay_date"
    t.boolean "dividend_share"
    t.boolean "dividend_yield"
    t.boolean "earnings_share"
    t.boolean "ebitda"
    t.boolean "eps_estimate_current_year"
    t.boolean "eps_estimate_next_quarter"
    t.boolean "eps_estimate_next_year"
    t.boolean "ex_dividend_date"
    t.boolean "fiftyday_moving_average"
    t.boolean "last_trade_date"
    t.boolean "last_trade_price_only"
    t.boolean "last_trade_time"
    t.boolean "last_trade_with_time"
    t.boolean "market_capitalization"
    t.boolean "name"
    t.boolean "oneyr_target_price"
    t.boolean "open"
    t.boolean "pe_ratio"
    t.boolean "peg_ratio"
    t.boolean "percebt_change_from_year_high"
    t.boolean "percent_change"
    t.boolean "percent_change_from_fiftyday_moving_average"
    t.boolean "percent_change_from_two_hundredday_moving_average"
    t.boolean "percent_change_from_year_low"
    t.boolean "previous_close"
    t.boolean "price_book"
    t.boolean "price_eps_estimate_current_year"
    t.boolean "price_eps_estimate_next_year"
    t.boolean "price_sales"
    t.boolean "response_code"
    t.boolean "short_ratio"
    t.boolean "stock_exchange"
    t.boolean "symbol"
    t.boolean "two_hundredday_moving_average"
    t.boolean "volume"
    t.boolean "year_high"
    t.boolean "year_low"
    t.boolean "year_range"
  end

  create_table "stocks", force: :cascade do |t|
    t.float    "ask"
    t.float    "average_daily_volume"
    t.float    "bid"
    t.float    "book_value"
    t.float    "change"
    t.float    "change_from_fiftyday_moving_average"
    t.float    "change_from_two_hundredday_moving_average"
    t.float    "change_from_year_high"
    t.float    "change_from_year_low"
    t.string   "change_percent_change"
    t.string   "changein_percent"
    t.string   "currency"
    t.float    "days_high"
    t.float    "days_low"
    t.string   "days_range"
    t.datetime "dividend_pay_date"
    t.float    "dividend_share"
    t.float    "dividend_yield"
    t.float    "earnings_share"
    t.string   "ebitda"
    t.float    "eps_estimate_current_year"
    t.float    "eps_estimate_next_quarter"
    t.float    "eps_estimate_next_year"
    t.datetime "ex_dividend_date"
    t.float    "fiftyday_moving_average"
    t.datetime "last_trade_date"
    t.float    "last_trade_price_only"
    t.string   "last_trade_time"
    t.string   "last_trade_with_time"
    t.string   "market_capitalization"
    t.string   "name"
    t.float    "oneyr_target_price"
    t.float    "open"
    t.float    "pe_ratio"
    t.float    "peg_ratio"
    t.string   "percebt_change_from_year_high"
    t.string   "percent_change"
    t.string   "percent_change_from_fiftyday_moving_average"
    t.string   "percent_change_from_two_hundredday_moving_average"
    t.string   "percent_change_from_year_low"
    t.float    "previous_close"
    t.float    "price_book"
    t.float    "price_eps_estimate_current_year"
    t.float    "price_eps_estimate_next_year"
    t.float    "price_sales"
    t.integer  "response_code"
    t.float    "short_ratio"
    t.string   "stock_exchange"
    t.string   "symbol"
    t.float    "two_hundredday_moving_average"
    t.float    "volume"
    t.float    "year_high"
    t.float    "year_low"
    t.string   "year_range"
    t.datetime "created_at",                                        null: false
    t.datetime "updated_at",                                        null: false
  end

  create_table "users", force: :cascade do |t|
    t.string   "username"
    t.string   "email"
    t.string   "phone"
    t.string   "password_digest"
    t.datetime "created_at",      null: false
    t.datetime "updated_at",      null: false
  end

end
