class Displaytext < ApplicationRecord
	def add_display_text
		# Formatting For Txt Message 
		self.avg_total_volume = "Avg. Total Volume"
        self.calculation_price = "Calculation Price"
        self.change = "Change"
        self.change_percent = "Percent Change"
        self.close = "Close"
        self.close_time = "Close Time"
        self.company_name = "Company Name"
        self.delayed_price = "Delayed Price"
        self.delayed_price_time = "Delayed Price Time"
        self.high = "High"
        self.latest_price = "Latest Price"
        self.latest_source = "Latest Source"
        self.latest_time = "Latest Time"
        self.latest_update = "Latest Update"
        self.latest_volume = "Latest Volume"
        self.low = "Low"
        self.market_cap = "Market Cap"
        self.open = "Open"
        self.open_time = "Open Time"
        self.pe_ratio = "P/E Ratio"
        self.previous_close = "Prev. Close"
        self.primary_exchange = "Primary Exchange"
        self.sector = "Sector"
        self.symbol = "Symbol"
        self.week52_high = "52 Wk. High"
        self.week52_low = "52 Wk. Low"
        self.ytd_change = "Year to Date Change" 
	end
end
